[default]
address = "0.0.0.0"
http_port = 8000
https_port = 8443
https = false
https_redirect = false
http3 = false
acme = false
certs = "$SAICMS_CONFIG/to/cert-chain.pem"
key = "$SAICMS_CONFIG/to/key.pem"
acme_cache = "path/to/acme-cache"
domain = "example.com"